# Generated by Django 6.0.3 on 2026-03-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarefa',
            name='arquivo_pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdfs/'),
        ),
        migrations.AddField(
            model_name='tarefa',
            name='resumo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
